name: CI/CD Pipeline

on:
  push:
    branches:
      - produccion

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  deploy:
    name: Deploy to Produccion
    needs: test
    if: github.ref == 'refs/heads/produccion' && needs.test.result == 'success'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Additional deployment steps go here
      # You can push your changes to the 'produccion' branch here

